### ISSUE TITLE
Add a static "About" page

### ISSUE THREAD

**Issue by n-kb** [jplusplus/oeko-kostenrechner#57]
With a markdown file for each language

**Comment by n-kb** [comment]
Possible to add a "Close" button to the about page? Otherwise user must go back to home page

**Comment by pirhoo** [comment]
WDYM a close button (ie where should it leads?) ? This is not a popup.

**Comment by n-kb** [comment]
Should lead to the visualization. Then maybe a "back to the visualization" button, like the one on the homepage?

**Comment by pirhoo** [comment]
This applies only when the user already have created vehicles. Also this is confusing if the user came from the home.

**Comment by n-kb** [comment]
ok.
